name: auris
description: Auris - 이명 관리 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  just_audio: ^0.9.40
  audio_session: ^0.1.21
  shared_preferences: ^2.3.2
  fl_chart: ^0.68.0
  intl: ^0.19.0
  uuid: ^4.4.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
